/**
 * ____________________________________________________________
 * 
 * ____________________________________________________________
 * 
 * @author Matej Đanić <matej.danic@triple-innovations.com>
 * @version 0.1
 * 
 * @created 7.5.2021.
 * ____________________________________________________________
 * 
*/

public enum BoxType {
    ONES,
    TWOS,
    THREES,
    FOURS,
    FIVES,
    SIXES,
    MAX,
    MIN,
    TRIPS,
    STRAIGHT,
    FULL,
    POKER,
    YAHTZEE
}
