/**
 * ____________________________________________________________
 * 
 * ____________________________________________________________
 * 
 * @author Matej Đanić <matej.danic@triple-innovations.com>
 * @version 0.1
 * 
 * @created 7.5.2021.
 * @modified 5.6.2021.
 * ____________________________________________________________
 * 
*/

public enum ColumnType {
    DOWNWARDS,
    UPWARDS,
    FREE,
    ANNOUNCEMENT
}
