public with sharing class Constants {
    public static final Integer NUMBER_OF_BOXES = 13;

    public static final Integer BONUS_TRIPS = 10;
    public static final Integer BONUS_STRAIGHT_SMALL = 35;
    public static final Integer BONUS_STRAIGHT_BIG = 45;
    public static final Integer BONUS_BOAT = 30;
    public static final Integer BONUS_CARRIAGE = 40;
    public static final Integer BONUS_YAMB = 50;

    public static final Integer NUMBERSUM_BONUS_THRESHOLD = 60;
    public static final Integer NUMBERSUM_BONUS = 30;
}
