public class GameConstants {

    public static final Integer NUMBER_OF_BOXES = 13;
    public static final Integer NUMBER_OF_DICE = 5;

    public static final Integer BONUS_TRIPS = 10;
    public static final Integer BONUS_STRAIGHT_SMALL = 35;
    public static final Integer BONUS_STRAIGHT_BIG = 45;
    public static final Integer BONUS_BOAT = 30;
    public static final Integer BONUS_CARRIAGE = 40;
    public static final Integer BONUS_YAMB = 50;

    public static final Integer NUMBERSUM_BONUS_THRESHOLD = 60;
    public static final Integer NUMBERSUM_BONUS = 30;

    public static final String ERROR_MESSAGE_ROLL_LIMIT_REACHED = 'The roll limit has been reached!';
    public static final String ERROR_MESSAGE_ANNOUNCEMENT_REQUIRED = 'An announcement is required!';
    public static final String ERROR_MESSAGE_ANNOUNCEMENT_ALREADY_DECLARED = 'An announcement has already been made!';
    public static final String ERROR_MESSAGE_ANNOUNCEMENT_NOT_AVAILABLE = 'An announcement is available only after first roll!';
    public static final String ERROR_MESSAGE_BOX_ALREADY_FILLED = 'The box has already been filled!';
    public static final String ERROR_MESSAGE_BOX_NOT_AVAILABLE = 'The box is not available!';
    public static final String ERROR_MESSAGE_DICE_ROLL_REQUIRED = 'To fill a box, the first dice roll is required!';
    public static final String ERROR_MESSAGE_BOX_NOT_ANNOUNCED = 'The box is different from announcement!';
    public static final String ERROR_MESSAGE_RESTART_FINISHED_GAME = 'A finished game cannot be restarted!';
}