/**
 * ____________________________________________________________
 * 
 * ____________________________________________________________
 * 
 * @author Matej Đanić <matej.danic@triple-innovations.com>
 * @version 0.1
 * 
 * @created 19.5.2021.
 * @modified 27.5.2021.
 * ____________________________________________________________
 * 
 */

public with sharing class GameConstants {

	public static final Integer NUMBER_OF_ROLLS = 3;
	public static final Integer NUMBER_OF_BOXES = 13;

	public static final Integer BONUS_TRIPS = 10;
	public static final Integer BONUS_STRAIGHT_SMALL = 35;
	public static final Integer BONUS_STRAIGHT_BIG = 45;
	public static final Integer BONUS_FULL = 30;
	public static final Integer BONUS_QUADS = 40;
	public static final Integer BONUS_YAMB = 50;

	public static final Integer NUMBERSUM_BONUS_THRESHOLD = 60;
	public static final Integer NUMBERSUM_BONUS = 30;
}
